name: custom action

inputs:
  path:
    description: "Whats your path"
    required: true

runs:
  using: 'composite'
  steps:
    - name: List files
      shell: bash
      run: |
        ls -ltr "${{ inputs.path }}" > /home/ubuntu/path.txt
