name: custom action
on:
  workflow_dispatch:
    inputs: 
      path:
        description: "Whats your path"
        required: true
jobs:
  list:
    runs-on: self-hosted
    steps:
      - name: list
        run: |
          ls -ltr ${{github.event.inputs.path}} > /home/ubuntu/path.txt

  
  
