name: secrets 
on:
  workflow_dispatch:
    inputs:
      secret:
        decsription: "Enter secret"
        required: true
jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - name: print
        if: secrets.NAME == 'Nikhil'
        shell: bash
        run: | 
          echo "Hello Nikhil"
      - name: printt
        if: ${{secrets.NAME}} != 'Nikhil'
        shell: bash
        run: | 
          echo "Hello you are unknown" 
