name: sielf hosted

on:
  push:

env:
  Name: nginx

jobs:
  install:
    runs-on: self-hosted
    steps:
      - name: Update and Install Nginx
        run: |
          sudo apt update -y
          sudo apt install ${{ env.Name }} -y
      - name: install webpage
        run: | 
          sudo echo "<h1> Im Devops Enigneer now </h1>" > /var/www/html/index.html
      - name: 
        run: |
          sudo systemctl restart nginx 
