name: sielf hosted

on:
  push:

env:
  Name: nginx

jobs:
  checkout:
    runs-on: self-hosted
    steps:
      - name: checkout 
        uses: actions/checkout@v4
  install:
    runs-on: self-hosted
    steps:
      - name: Update and Install Nginx
        run: |
          sudo apt update -y
          sudo apt install ${{ env.Name }} -y
      - name: install webpage
        run: | 
          echo "<h1> Hello I'm Devops Engineer now </h1>" | sudo tee /var/www/html/index.html
      - name: 
        run: |
          sudo systemctl restart nginx 
