name: User inputs
on: 
  workflow_dispatch:
    inputs:
      name:
        description: "Enter your name"
        default: "Admin"
        required: true
      age:
        description: "Whats your age"
        required: true
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: handle minor
        if: ${{github.event.inputs.age < 18}}
        run: echo "you are minor"
      - name: handle adult
        if: ${{github.event.inputs.age > 18}}
        run: echo "Hello ${{ github.event.inputs.name }}, you are in!"
