name: User inputs

on:
  workflow_call:
    inputs:
      name:
        description: "Enter your name"
        default: "Admin"
        required: true
        type: string
      age:
        description: "Whats your age"
        required: true
        type: number

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: handle minor
        # Condition: Age is strictly less than 18
        if: ${{ github.event.inputs.age < 18 }}
        run: echo "you are minor"

      - name: handle adult
        # Condition: Age is 18 or older
        if: ${{ github.event.inputs.age >= 18 }}
        run: echo "Hello ${{ github.event.inputs.name }}.. you are in!"
